ame: rapids-23.12
channels:
  - pytorch
  - anaconda
  - nvidia
  - rapidsai
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - aiohttp=3.9.1
  - aiosignal=1.3.1
  - annotated-types=0.6.0
  - ansi2html=1.9.1
  - anyio=4.2.0
  - aom=3.7.1
  - appdirs=1.4.4
  - argon2-cffi=23.1.0
  - argon2-cffi-bindings=21.2.0
  - arrow=1.3.0
  - asttokens=2.4.1
  - async-lru=2.0.4
  - async-timeout=4.0.3
  - attrs=23.2.0
  - aws-c-auth=0.7.11
  - aws-c-cal=0.6.9
  - aws-c-common=0.9.12
  - aws-c-compression=0.2.17
  - aws-c-event-stream=0.4.1
  - aws-c-http=0.8.0
  - aws-c-io=0.14.0
  - aws-c-mqtt=0.10.1
  - aws-c-s3=0.4.9
  - aws-c-sdkutils=0.1.13
  - aws-checksums=0.1.17
  - aws-crt-cpp=0.26.0
  - aws-sdk-cpp=1.11.210
  - azure-core-cpp=1.10.3
  - azure-storage-blobs-cpp=12.10.0
  - azure-storage-common-cpp=12.5.0
  - babel=2.14.0
  - bayesian-optimization=1.4.3
  - beautifulsoup4=4.12.3
  - black=23.11.0
  - bleach=6.1.0
  - blinker=1.7.0
  - blosc=1.21.5
  - bokeh=3.3.3
  - branca=0.7.0
  - brotli=1.1.0
  - brotli-bin=1.1.0
  - brotli-python=1.1.0
  - brunsli=0.1
  - bzip2=1.0.8
  - c-ares=1.25.0
  - c-blosc2=2.13.1
  - ca-certificates=2023.12.12
  - cached-property=1.5.2
  - cached_property=1.5.2
  - cachetools=5.3.2
  - cairo=1.18.0
  - certifi=2023.11.17
  - cffi=1.16.0
  - cfitsio=4.3.1
  - charls=2.4.2
  - charset-normalizer=3.3.2
  - click=8.1.7
  - click-plugins=1.1.1
  - cligj=0.7.2
  - cloudpickle=3.0.0
  - colorama=0.4.6
  - colorcet=3.0.1
  - comm=0.2.1
  - contourpy=1.2.0
  - cubinlinker=0.3.0
  - cucim=23.12.01
  - cuda-cudart=11.8.89
  - cuda-cupti=11.8.87
  - cuda-libraries=11.8.0
  - cuda-nvrtc=11.8.89
  - cuda-nvtx=11.8.86
  - cuda-profiler-api=11.8.86
  - cuda-python=11.8.3
  - cuda-runtime=11.8.0
  - cuda-version=11.8
  - cudatoolkit=11.8.0
  - cudf=23.12.01
  - cudf_kafka=23.12.01
  - cudnn=8.8.0.121
  - cugraph=23.12.00
  - cuml=23.12.00
  - cuproj=23.12.01
  - cupy=13.0.0
  - cupy-core=13.0.0
  - cuspatial=23.12.01
  - custreamz=23.12.01
  - cuxfilter=23.12.00
  - cycler=0.12.1
  - cyrus-sasl=2.1.27
  - cytoolz=0.12.2
  - dash=2.14.2
  - dask=2023.11.0
  - dask-core=2023.11.0
  - dask-cuda=23.12.00
  - dask-cudf=23.12.01
  - dask-glm=0.3.2
  - dask-ml=2023.3.24
  - dask-sql=2023.11.0
  - datashader=0.16.0
  - dav1d=1.2.1
  - debugpy=1.8.0
  - decorator=5.1.1
  - defusedxml=0.7.1
  - distributed=2023.11.0
  - dlpack=0.5
  - entrypoints=0.4
  - exceptiongroup=1.2.0
  - executing=2.0.1
  - expat=2.5.0
  - fastapi=0.103.0
  - fastrlock=0.8.2
  - filelock=3.13.1
  - fiona=1.9.5
  - flask=3.0.1
  - fmt=9.1.0
  - folium=0.15.1
  - font-ttf-dejavu-sans-mono=2.37
  - font-ttf-inconsolata=3.000
  - font-ttf-source-code-pro=2.038
  - font-ttf-ubuntu=0.83
  - fontconfig=2.14.2
  - fonts-conda-ecosystem=1
  - fonts-conda-forge=1
  - fonttools=4.47.2
  - fqdn=1.5.1
  - freetype=2.12.1
  - freexl=2.0.0
  - frozenlist=1.4.1
  - fsspec=2023.12.2
  - gdal=3.8.1
  - gdk-pixbuf=2.42.10
  - geopandas=0.14.2
  - geopandas-base=0.14.2
  - geos=3.12.1
  - geotiff=1.7.1
  - gettext=0.21.1
  - gflags=2.2.2
  - giflib=5.2.1
  - glog=0.6.0
  - gmock=1.14.0
  - gmp=6.3.0
  - gmpy2=2.1.2
  - graphistry=0.33.0
  - gtest=1.14.0
  - h11=0.14.0
  - h2=4.1.0
  - hdf4=4.2.15
  - hdf5=1.14.3
  - holoviews=1.18.1
  - hpack=4.0.0
  - httpcore=1.0.2
  - httpx=0.26.0
  - hyperframe=6.0.1
  - icu=73.2
  - idna=3.6
  - imagecodecs=2024.1.1
  - imageio=2.33.1
  - importlib-metadata=7.0.1
  - importlib_metadata=7.0.1
  - importlib_resources=6.1.1
  - ipykernel=6.29.0
  - ipython=8.20.0
  - ipywidgets=8.0.4
  - isoduration=20.11.0
  - itsdangerous=2.1.2
  - jbig=2.1
  - jedi=0.19.1
  - jinja2=3.1.3
  - joblib=1.3.2
  - json-c=0.17
  - json5=0.9.14
  - jsonpointer=2.4
  - jsonschema=4.21.1
  - jsonschema-specifications=2023.12.1
  - jsonschema-with-format-nongpl=4.21.1
  - jupyter-lsp=2.2.2
  - jupyter-server-proxy=4.1.0
  - jupyter_client=8.6.0
  - jupyter_core=5.7.1
  - jupyter_events=0.9.0
  - jupyter_server=2.12.5
  - jupyter_server_terminals=0.5.2
  - jupyterlab=4.0.11
  - jupyterlab_pygments=0.3.0
  - jupyterlab_server=2.25.2
  - jupyterlab_widgets=3.0.9
  - jxrlib=1.1
  - kealib=1.5.3
  - keyutils=1.6.1
  - kiwisolver=1.4.5
  - krb5=1.21.2
  - lazy_loader=0.3
  - lcms2=2.16
  - ld_impl_linux-64=2.40
  - lerc=4.0.0
  - libabseil=20230802.1
  - libaec=1.1.2
  - libarchive=3.7.2
  - libarrow=14.0.2
  - libarrow-acero=14.0.2
  - libarrow-dataset=14.0.2
  - libarrow-flight=14.0.2
  - libarrow-flight-sql=14.0.2
  - libarrow-gandiva=14.0.2
  - libarrow-substrait=14.0.2
  - libavif16=1.0.3
  - libblas=3.9.0
  - libboost-headers=1.84.0
  - libbrotlicommon=1.1.0
  - libbrotlidec=1.1.0
  - libbrotlienc=1.1.0
  - libcblas=3.9.0
  - libcrc32c=1.1.2
  - libcublas=11.11.3.6
  - libcublas-dev=11.11.3.6
  - libcucim=23.12.01
  - libcudf=23.12.01
  - libcudf_kafka=23.12.01
  - libcufft=10.9.0.58
  - libcufile=1.4.0.31
  - libcufile-dev=1.4.0.31
  - libcugraph=23.12.00
  - libcugraph_etl=23.12.00
  - libcugraphops=23.12.00
  - libcuml=23.12.00
  - libcumlprims=23.12.00
  - libcurand=10.3.0.86
  - libcurand-dev=10.3.0.86
  - libcurl=8.5.0
  - libcusolver=11.4.1.48
  - libcusolver-dev=11.4.1.48
  - libcusparse=11.7.5.86
  - libcusparse-dev=11.7.5.86
  - libcuspatial=23.12.01
  - libdeflate=1.19
  - libedit=3.1.20191231
  - libev=4.33
  - libevent=2.1.12
  - libexpat=2.5.0
  - libffi=3.4.2
  - libgcc-ng=13.2.0
  - libgdal=3.8.1
  - libgfortran-ng=13.2.0
  - libgfortran5=13.2.0
  - libglib=2.78.3
  - libgoogle-cloud=2.12.0
  - libgrpc=1.59.3
  - libhwloc=2.9.3
  - libiconv=1.17
  - libjpeg-turbo=3.0.0
  - libkml=1.3.0
  - libkvikio=23.12.00
  - liblapack=3.9.0
  - libllvm14=14.0.6
  - libllvm15=15.0.7
  - libmagma=2.7.2
  - libmagma_sparse=2.7.2
  - libnetcdf=4.9.2
  - libnghttp2=1.58.0
  - libnl=3.9.0
  - libnpp=11.8.0.86
  - libnsl=2.0.1
  - libntlm=1.4
  - libnuma=2.0.16
  - libnvjpeg=11.9.0.86
  - libopenblas=0.3.26
  - libparquet=14.0.2
  - libpng=1.6.39
  - libpq=16.1
  - libprotobuf=4.24.4
  - libraft=23.12.00
  - libraft-headers=23.12.00
  - libraft-headers-only=23.12.00
  - librdkafka=1.9.2
  - libre2-11=2023.06.02
  - librmm=23.12.00
  - librttopo=1.1.0
  - libsodium=1.0.18
  - libspatialindex=1.9.3
  - libspatialite=5.1.0
  - libsqlite=3.44.2
  - libssh2=1.11.0
  - libstdcxx-ng=13.2.0
  - libthrift=0.19.0
  - libtiff=4.6.0
  - libtorch=2.1.0
  - libutf8proc=2.8.0
  - libuuid=2.38.1
  - libuv=1.46.0
  - libwebp=1.3.2
  - libwebp-base=1.3.2
  - libxcb=1.15
  - libxcrypt=4.4.36
  - libxgboost=1.7.6
  - libxml2=2.12.4
  - libzip=1.10.1
  - libzlib=1.2.13
  - libzopfli=1.0.3
  - linkify-it-py=2.0.2
  - llvm-openmp=17.0.6
  - llvmlite=0.40.1
  - locket=1.0.0
  - lz4=4.3.3
  - lz4-c=1.9.4
  - lzo=2.10
  - magma=2.7.2
  - mapclassify=2.6.1
  - markdown=3.5.2
  - markdown-it-py=3.0.0
  - markupsafe=2.1.4
  - matplotlib-base=3.8.2
  - matplotlib-inline=0.1.6
  - mdit-py-plugins=0.4.0
  - mdurl=0.1.2
  - minizip=4.0.4
  - mistune=3.0.2
  - mkl=2023.2.0
  - mpc=1.3.1
  - mpfr=4.2.1
  - mpmath=1.3.0
  - msgpack-python=1.0.7
  - multidict=6.0.4
  - multipledispatch=0.6.0
  - munkres=1.1.4
  - mypy_extensions=1.0.0
  - nb_black=1.0.7
  - nbclient=0.8.0
  - nbconvert-core=7.14.2
  - nbformat=5.9.2
  - nccl=2.19.4.1
  - ncurses=6.4
  - nest-asyncio=1.6.0
  - networkx=3.2.1
  - nodejs=20.9.0
  - noise=1.2.2
  - notebook-shim=0.2.3
  - nspr=4.35
  - nss=3.97
  - numba=0.57.1
  - numpy=1.23.4
  - nvcomp=3.0.4
  - nvtx=0.2.8
  - openjpeg=2.5.0
  - openslide=3.4.1
  - openssl=3.2.0
  - orc=1.9.2
  - overrides=7.6.0
  - packaging=23.2
  - palettable=3.3.3
  - pandas=1.5.3
  - pandocfilters=1.5.0
  - panel=1.3.7
  - param=2.0.2
  - parso=0.8.3
  - partd=1.4.1
  - pathspec=0.10.3
  - patsy=0.5.6
  - pcre2=10.42
  - pexpect=4.9.0
  - pickleshare=0.7.5
  - pillow=10.2.0
  - pip=23.3.2
  - pixman=0.43.0
  - pkgutil-resolve-name=1.3.10
  - platformdirs=4.1.0
  - plotly=5.18.0
  - poppler=23.12.0
  - poppler-data=0.4.12
  - postgresql=16.1
  - proj=9.3.0
  - prometheus_client=0.19.0
  - prompt-toolkit=3.0.42
  - protobuf=4.24.4
  - psutil=5.9.8
  - pthread-stubs=0.4
  - ptxcompiler=0.8.1
  - ptyprocess=0.7.0
  - pure_eval=0.2.2
  - py-xgboost=1.7.6
  - pyaml=23.12.0
  - pyarrow=14.0.2
  - pyarrow-hotfix=0.6
  - pycparser=2.21
  - pyct=0.5.0
  - pyct-core=0.5.0
  - pydantic=2.5.3
  - pydantic-core=2.14.6
  - pyee=8.1.0
  - pygments=2.17.2
  - pylibcugraph=23.12.00
  - pylibraft=23.12.00
  - pynvml=11.4.1
  - pyparsing=3.1.1
  - pyppeteer=1.0.2
  - pyproj=3.6.1
  - pysocks=1.7.1
  - python=3.10.13
  - python-confluent-kafka=1.9.2
  - python-dateutil=2.8.2
  - python-fastjsonschema=2.19.1
  - python-json-logger=2.0.7
  - python_abi=3.10
  - pytorch=2.1.0
  - pytorch-cuda=11.8
  - pytorch-mutex=1.0
  - pytz=2023.3.post1
  - pyviz_comms=3.0.0
  - pywavelets=1.4.1
  - pyyaml=6.0.1
  - pyzmq=25.1.2
  - raft-dask=23.12.00
  - rapids=23.12.00
  - rapids-dask-dependency=23.12.01
  - rapids-xgboost=23.12.00
  - rav1e=0.6.6
  - rdma-core=49.0
  - re2=2023.06.02
  - readline=8.2
  - referencing=0.32.1
  - requests=2.31.0
  - retrying=1.3.3
  - rfc3339-validator=0.1.4
  - rfc3986-validator=0.1.1
  - rich=13.7.0
  - rmm=23.12.00
  - rpds-py=0.17.1
  - rtree=1.2.0
  - s2n=1.4.1
  - scikit-image=0.21.0
  - scikit-learn=1.4.0
  - scikit-optimize=0.9.0
  - scipy=1.12.0
  - seaborn=0.13.1
  - seaborn-base=0.13.1
  - send2trash=1.8.2
  - setuptools=69.0.3
  - shapely=2.0.2
  - simpervisor=1.0.0
  - six=1.16.0
  - skorch=0.15.0
  - sleef=3.5.1
  - snappy=1.1.10
  - sniffio=1.3.0
  - sortedcontainers=2.4.0
  - soupsieve=2.5
  - sparse=0.15.1
  - spdlog=1.11.0
  - sqlite=3.44.2
  - squarify=0.4.3
  - stack_data=0.6.2
  - starlette=0.27.0
  - statsmodels=0.14.1
  - streamz=0.6.4
  - svt-av1=1.8.0
  - sympy=1.12
  - tabulate=0.9.0
  - tbb=2021.11.0
  - tblib=3.0.0
  - tenacity=8.2.3
  - terminado=0.18.0
  - threadpoolctl=3.2.0
  - tifffile=2023.12.9
  - tiledb=2.18.4
  - tinycss2=1.2.1
  - tk=8.6.13
  - tomli=2.0.1
  - toolz=0.12.1
  - torchaudio=2.1.0
  - torchvision=0.16.1
  - tornado=6.3.3
  - tqdm=4.66.1
  - traitlets=5.14.1
  - treelite=3.9.1
  - types-python-dateutil=2.8.19.20240106
  - typing-extensions=4.9.0
  - typing_extensions=4.9.0
  - typing_utils=0.1.0
  - tzcode=2023d
  - tzdata=2023d
  - tzlocal=5.2
  - uc-micro-py=1.0.2
  - ucx=1.15.0
  - ucx-proc=1.0.0
  - ucx-py=0.35.00
  - unicodedata2=15.1.0
  - uri-template=1.3.0
  - uriparser=0.9.7
  - urllib3=1.26.18
  - uvicorn=0.27.0
  - wcwidth=0.2.13
  - webcolors=1.13
  - webencodings=0.5.1
  - websocket-client=1.7.0
  - websockets=10.4
  - werkzeug=3.0.1
  - wheel=0.42.0
  - widgetsnbextension=4.0.5
  - xarray=2024.1.1
  - xarray-spatial=0.3.7
  - xerces-c=3.2.5
  - xgboost=1.7.6
  - xorg-kbproto=1.0.7
  - xorg-libice=1.1.1
  - xorg-libsm=1.2.4
  - xorg-libx11=1.8.7
  - xorg-libxau=1.0.11
  - xorg-libxdmcp=1.1.3
  - xorg-libxext=1.3.4
  - xorg-libxrender=0.9.11
  - xorg-renderproto=0.11.1
  - xorg-xextproto=7.3.0
  - xorg-xproto=7.0.31
  - xyzservices=2023.10.1
  - xz=5.2.6
  - yaml=0.2.5
  - yarl=1.9.4
  - zeromq=4.3.5
  - zfp=1.0.1
  - zict=3.0.0
  - zipp=3.17.0
  - zlib=1.2.13
  - zlib-ng=2.0.7
  - zstd=1.5.5
  - pip:
      - ray==2.9.1
      - tensorboardx==2.6.2.2
      - treelite-runtime==3.9.1
