name: rapids-23.12
channels:
  - pytorch
  - anaconda
  - nvidia
  - rapidsai
  - conda-forge
  - defaults
dependencies:
  - rapids=23.12
  - python=3.10
  - cuda-version=11.8
  - dask-sql
  - jupyterlab
  - dash
  - graphistry
  - xarray-spatial
  - pytorch
  - dask-ml
  - ipykernel
  - bayesian-optimization
  - scikit-optimize
  - seaborn
  - torchvision
  - torchaudio
  - pytorch-cuda=11.8
  - skorch
  - conda-forge::nb_black
  - ipywidgets
  - ca-certificates
  - certifi
  - openssl
  - code-server
  - nbgitpuller
  - pip
  - pip:
      - ray==2.9.1

