name: rapids-23.10
channels:
  - nvidia
  - rapidsai
  - conda-forge
  - defaults
dependencies:
  - rapids=23.10
  - python=3.10
  - cuda-version=11.8
  - ipykernel
  - ca-certificates
  - certifi
  - openssl
  - tabulate
  - nb_black
  - bayesian-optimization
  - scikit-optimize
  - ipywidgets
  - dask-ml
  - seaborn
  - pip
  - pip:
      - filelock==3.13.1
      - mpmath==1.3.0
      - ray==2.8.0
      - skorch==0.15.0
      - sympy==1.12
      - tensorboardx==2.6.2.2
      - torch==2.1.0+cu118
      - torchaudio==2.1.0+cu118
      - torchvision==0.16.0+cu118
      - treelite-runtime==3.9.1
      - triton==2.1.0
